; Agent's Optimization Mod v2.0 - Device Profile Overrides
[Windows DeviceProfile]
DeviceType=Windows
BaseProfileName=
+CVars=r.VT.MaxUploadsPerFrame=2
+CVars=r.VT.MaxUploadsPerFrameInEditor=2
+CVars=r.DFShadowQuality=1
+CVars=r.VolumetricRenderTarget.Mode=1
+CVars=r.TemporalAA.Algorithm=1
+CVars=r.Streaming.HLODStrategy=0
+CVars=r.Streaming.FullyLoadUsedTextures=0
+CVars=r.Streaming.DefragDynamicBounds=1
+CVars=r.Streaming.MaxEffectiveScreenSize=0