; Agent's Optimization Mod v2.0 - Engine Renderer Overrides
[/Script/Engine.RendererSettings]
r.RayTracing=False
r.RayTracing.UseTextureLod=False
r.RayTracing.GlobalIllumination=0
r.RayTracing.AmbientOcclusion=0
r.RayTracing.Reflections=0
r.RayTracing.Shadows=0
r.RayTracing.Translucency=0
r.RTXGI.DDGI=false
r.GlobalIllumination.ExperimentalPlugin=false
r.DFShadowCullTileWorldSize=15000
r.DFShadowQuality=0
r.Shadow.PointLightDepthBias=0.06
r.ShadowFilterMethod=0
r.GenerateMeshDistanceFields=False
r.VT.TileSize=128
r.vt.FeedbackFactor=8
r.SeparateTranslucency=False
r.OcclusionQueryLocation=1
r.RayTracing.Geometry.NiagaraSprites=0
r.RayTracing.Geometry.StaticMeshes.WPO=0
r.RayTracing.Geometry.SkeletalMeshes=0
r.ReflectionCaptureResolution=256

[/Script/Engine.Engine]
bSmoothFrameRate=False